config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  get 'products' => 'products#index'

  resources :products do
    resources :reviews, :except => [:show, :index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, :cost, :country, presence: true
  validates :cost, numericality: { greater_than: 0 }

  scope :recent, -> { order(created_at: :desc).limit(3) }
  scope :most_reviewed, -> {(
    select("products.id, products.name, products.cost, products.country, count(reviews.id) as reviews_count")
    .left_outer_joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .first
  )}
  scope :usa_made, -> { where(country: "United States of America") }

  def rating
    if self.reviews.any?
      rating_total = self.reviews.reduce(0) do |total, review|
        total + review.rating
      end
      return rating_total.to_f / self.reviews.length
    else
      return nil
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :content, :rating, :product, presence: true
  validates :rating, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  validates :content, length: { in: 50..250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!";
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!";
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

private

  def product_params
    params.require(:product).permit(:name, :cost, :country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end
private

  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="contain-to-grid sticky">
      <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
        <ul class="title-area">
          <li class="name">
            <h1 class="left"><a href="/">Marios</a></h1>
            <h1 class="left"><a href="/products">Products</a></h1>
          </li>
        </ul>
      </nav>
    </div>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="center pad">
  <%= image_tag 'buffet.jpg', size: "600x400", alt: "buffet" %>
</div>

<div class="parent">

  <div class="left-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>

  <div class="middle-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
  
  <div class="right-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
</div>

app/views/products/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="center">
  
  <h1>Products</h1>

  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>

  <hr>

  <%= link_to "New Product", new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="center">
  
  <h1><%= @product.name %></h1>

  <% if @product.reviews.any? %>

    <ul>
      <% @product.reviews.each do |review| %>
        <li>
          <br>
          <%= review.content %>
          <br>
          Rating: <%= review.rating %>
          <br>
          Reviewer: <%= review.author %>
          <br>
          <%= link_to "Edit", edit_product_review_path(@product, review) %> |
          <%= link_to "Delete", product_review_path(@product, review),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
          <br>
          <br>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no reviews yet!</p>
  <% end %>

  <p><%= link_to "Write a review", new_product_review_path(@product) %></p>
  <p><%= link_to "Delete product", product_path(@product),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/reviews/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: @review} %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>

<%= render 'form' %>